# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 2.7
        env: TOX_ENV=py27-tests
      - python: 3.5
        env: TOX_ENV=py35-tests
      - python: 3.6
        env: TOX_ENV=py36-tests
      - python: 3.7
        env: TOX_ENV=py37-tests
      - python: 3.7
        env: TOX_ENV=pylint

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
