# Config file for automatic testing at travis-ci.org

sudo: false
language: python
cache: pip

matrix:
  include:
    - python: 3.7
      env: TOX_ENV=pylint
    - python: 3.7
      env: TOX_ENV=mypy
    - python: 2.7
      env: TOX_ENV=py27-tests
    - python: 3.5
      env: TOX_ENV=py35-tests
    - python: 3.6
      env: TOX_ENV=py36-tests
    - python: 3.7
      env: TOX_ENV=py37-tests

services:
  - docker

before_install:
  - docker run -p 8200:8200 -d --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=test_root_token' vault:0.9.6

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

after_success:
  - codecov
